
package bodega_myc_.Vista;


public class MENU_PRINCIPAL extends javax.swing.JFrame {

 
    public MENU_PRINCIPAL() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        Productojd = new javax.swing.JMenuItem();
        InventarioJd = new javax.swing.JMenuItem();
        clientesJd = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        ProveedoresJd = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        detalleFactujd = new javax.swing.JMenuItem();
        comprasJD = new javax.swing.JMenuItem();
        jdFactura = new javax.swing.JMenuItem();
        jdReportesClientes = new javax.swing.JMenuItem();
        jdReportesCompras = new javax.swing.JMenuItem();
        jdReporteVentas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        SalirJd = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/BODEGA M Y C.png"))); // NOI18N

        jMenu2.setText("ADMINISTRAR");

        Productojd.setText("PROCUCTOS");
        Productojd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductojdActionPerformed(evt);
            }
        });
        jMenu2.add(Productojd);

        InventarioJd.setText("INVENTARIO");
        InventarioJd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventarioJdActionPerformed(evt);
            }
        });
        jMenu2.add(InventarioJd);

        clientesJd.setText("CLIENTES");
        clientesJd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesJdActionPerformed(evt);
            }
        });
        jMenu2.add(clientesJd);

        jMenuBar1.add(jMenu2);

        jMenu6.setText("PROVEDORES");

        ProveedoresJd.setText("PROVEDORES");
        ProveedoresJd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProveedoresJdActionPerformed(evt);
            }
        });
        jMenu6.add(ProveedoresJd);

        jMenuBar1.add(jMenu6);

        jMenu3.setText("REPORTES");

        detalleFactujd.setText("DETALLE FACTURA");
        detalleFactujd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detalleFactujdActionPerformed(evt);
            }
        });
        jMenu3.add(detalleFactujd);

        comprasJD.setText("COMPRAS");
        comprasJD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprasJDActionPerformed(evt);
            }
        });
        jMenu3.add(comprasJD);

        jdFactura.setText("FACTURA");
        jdFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdFacturaActionPerformed(evt);
            }
        });
        jMenu3.add(jdFactura);

        jdReportesClientes.setText("REPORTE CLIENTES");
        jdReportesClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdReportesClientesActionPerformed(evt);
            }
        });
        jMenu3.add(jdReportesClientes);

        jdReportesCompras.setText("REPORTE COMPRAS");
        jdReportesCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdReportesComprasActionPerformed(evt);
            }
        });
        jMenu3.add(jdReportesCompras);

        jdReporteVentas.setText("REPORTE VENTAS");
        jdReporteVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdReporteVentasActionPerformed(evt);
            }
        });
        jMenu3.add(jdReporteVentas);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("SALIR");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        SalirJd.setText("EXIT");
        SalirJd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirJdActionPerformed(evt);
            }
        });
        jMenu4.add(SalirJd);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 769, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InventarioJdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventarioJdActionPerformed
        
    }//GEN-LAST:event_InventarioJdActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void ProductojdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductojdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductojdActionPerformed

    private void ProveedoresJdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProveedoresJdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProveedoresJdActionPerformed

    private void detalleFactujdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detalleFactujdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detalleFactujdActionPerformed

    private void comprasJDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprasJDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comprasJDActionPerformed

    private void SalirJdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirJdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirJdActionPerformed

    private void jdFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jdFacturaActionPerformed

    private void clientesJdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesJdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientesJdActionPerformed

    private void jdReportesComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdReportesComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jdReportesComprasActionPerformed

    private void jdReporteVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdReporteVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jdReporteVentasActionPerformed

    private void jdReportesClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdReportesClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jdReportesClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU_PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU_PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU_PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU_PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU_PRINCIPAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem InventarioJd;
    public javax.swing.JMenuItem Productojd;
    public javax.swing.JMenuItem ProveedoresJd;
    public javax.swing.JMenuItem SalirJd;
    public javax.swing.JMenuItem clientesJd;
    public javax.swing.JMenuItem comprasJD;
    public javax.swing.JMenuItem detalleFactujd;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JMenu jMenu2;
    public javax.swing.JMenu jMenu3;
    public javax.swing.JMenu jMenu4;
    public javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jdFactura;
    public javax.swing.JMenuItem jdReporteVentas;
    public javax.swing.JMenuItem jdReportesClientes;
    public javax.swing.JMenuItem jdReportesCompras;
    // End of variables declaration//GEN-END:variables
}
